$(shell mkdir -p /home/jenkins/slaves/workspace/V8R2C52_ALE_kernel/android_code/device/hisi/customize/build_script/../../../../out/target/product/hi6210sft/obj/KERNEL_OBJ/arch/arm64/boot/dts/auto-generate/hi6220)
include /home/jenkins/slaves/workspace/V8R2C52_ALE_kernel/android_code/device/hisi/customize/build_script/../../../../kernel/arch/arm64/boot/dts/auto-generate/hi6220/hi6220_dtb.mk
dtbs: hi6220_dtb
